# Generated by Django 6.0.6 on 2026-06-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity_required',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
