# Generated by Django 6.0.6 on 2026-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=5)),
                ('quantity_available', models.PositiveIntegerField()),
                ('minimum_quantity', models.PositiveIntegerField()),
                ('cost_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=100)),
                ('last_restocked', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
