# Generated by Django 6.0.6 on 2026-06-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
